/** `.env.ts` is generated by the `npm run env` command */
import env from './.env';

/** environment de produção */
export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '',
  apiVersion: '1',
  envName: 'PROD',
  API_URL: 'assets/api'
};
